# Setup
title: Spegman's Every Ref.
description: 'A collection of useful and interesting facts, figures and charts.'

logo: /public/favicon.png

markdown: kramdown
plugins:
  - jekyll-seo-tag


# About/contact
owner:
  name: Ibraheem Rodrigues
  url: https://ibraheemrodrigues.com
  email: contact@ibraheemrodrigues.com

repository: ibraheemr/spegmans-every-ref

# Collections
collections:
  content:
    output: true
    permalink: /:path
    category: false

defaults:
  -
    values:
      layout: "page"
